version: '2'

services:
  backend:
    build: .
    ports:
      - 3333:3333
      - 9229:9229 # debugger port

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    command: yarn dev

    environment:
      PORT: 3333
      DATABASE_URL: postgres://docker:docker@postgres:5432/db_name_dev

    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db_name_dev
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_HOST_AUTH_METHOD: trust
