version: '2'

services:
  backend:
    build: .
    ports:
      - 3333:3333
      - 9229:9229 # debugger port

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    command: yarn dev

    environment:
      PORT: 3333
