version: '3'

services:
  web:
    container_name: ng_cash_web
    image: ng-cash-web
    restart: unless-stopped
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./web/src:/app/web/src
      - ./web/public:/app/web/public
    environment:
      NEXT_PUBLIC_API_URL: http://host.docker.internal:3333/api
      NEXT_PUBLIC_AUTH_COOKIE_NAME: '@ng-cash-challenge:token'
    networks:
      - ng_cash_network
    depends_on:
      - api
    command: yarn dev

  api:
    container_name: ng_cash_api
    image: ng-cash-api
    restart: always
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - 3333:3333
      - 9229:9229 # debugger
    volumes:
      - ./api:/app/api
      - /app/api/node_modules
    environment:
      PORT: 3333
      DATABASE_URL: postgres://docker:docker@postgres:5432/ng_cash_dev
      JWT_SECRET: tu1nKMiTuT0m+Wzyb28iiYLobmJNowZ4ltu7WHrfKGM=
    networks:
      - ng_cash_network
    depends_on:
      - postgres
    command: yarn dev

  postgres:
    container_name: ng_cash_db
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ng_cash_dev
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - ./api/pgdata:/var/lib/postgresql/data
    networks:
      - ng_cash_network

networks:
  ng_cash_network:
